config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show, :update, :edit]
  resources :habits, only: [:index, :new, :create, :show]
  resources :groups, only: [:index, :new, :create, :show]
  resources :repeat_days, only: [:create, :destroy]

  get '/external_habits', to: 'habits#external_habits'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'sessions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :group_habits, dependent: :destroy
  has_many :habits, through: :group_habits

  validates :name, uniqueness: true
end

app/models/group_habit.rb
class GroupHabit < ApplicationRecord
  belongs_to :group
  belongs_to :habit
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :repeat_days
  has_many :group_habits, dependent: :destroy
  has_many :groups, through: :group_habits
  accepts_nested_attributes_for :groups, allow_destroy: true

  validates :name, :time, presence: true
  validates :time, numericality: { greater_than: 0 }
end

app/models/repeat_day.rb
class RepeatDay < ApplicationRecord
  belongs_to :habit
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :habits
  has_many :groups
  has_one_attached :avatar
  validates :name, presence: true, length: { in: 3..10 }
  validates :name, uniqueness: true
  validates :name, format: { with: /[a-zA-Z0-9]/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_login
  helper_method :format_date
  helper_method :authenticate_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_login
    !current_user.nil?
  end

  def format_date(date)
    return unless date.is_a?(Date)

    year = date.year
    month = Date::MONTHNAMES[date.month]

    day_of_month = date.mday.to_s
    last_dig = date.mday.digits[0]
    day_of_month << 'th' unless [1, 2, 3].include?(last_dig)
    day_of_month << 'st' if last_dig == 1
    day_of_month << 'nd' if last_dig == 2
    day_of_month << 'rd' if last_dig == 3

    day_of_week = Date::DAYNAMES[date.wday]

    "#{day_of_week}, #{day_of_month} #{month} #{year}"
  end

  def authenticate_user
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper
  before_action :authenticate_user

  def index
    @groups = Group.all.includes(avatar_attachment: [:blob])
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      @group.avatar.attach(params[:group][:avatar])
      redirect_to group_path(@group), notice: 'Group was successfully created.'
    else
      flash[:alert] = @group.errors.full_messages.first
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @habits = @group.habits.includes(user: [avatar_attachment: :blob])
  end

  private

  def group_params
    params.require(:group).permit(:name, :avatar)
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user
  include HabitsHelper
  include GroupsHelper

  def index
    @habits = Habit.all.includes(:repeat_days)
  end

  def new
    @habit = current_user.habits.new
    @habit.groups.build
    @groups = Group.all
  end

  def create
    @habit = current_user.habits.new(habit_params.reject { |key, _value| key == 'group_id' })
    if @habit.save
      GroupHabit.create(habit_id: @habit.id, group_id: habit_params[:group_id])
      redirect_to habit_path({ id: @habit.id }), notice: 'Habit successfully created.'
    else
      flash.now[:alert] = @habit.errors.full_messages.first
      render :new
    end
  end

  def show
    @habit = Habit.find(params[:id])
  end

  def external_habits
    groups = Group.where(name: '')
    @habits = groups.map(&:habits)
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :amount, :time, :group_id)
  end
end

app/controllers/repeat_days_controller.rb
class RepeatDaysController < ApplicationController
  before_action :authenticate_user
  def create
    @repeat_days = RepeatDay.new(day: params[:day], user_id: current_user.id, habit_id: params[:habit_id])
    @repeat_days.save
    redirect_to habit_path(params[:habit_id])
  end

  def destroy
    @repeat_days = RepeatDay.find_by(day: params[:day], user_id: current_user.id)
    if @repeat_days.delete
      flash[:success] = 'Day was successfully deleted.'
      redirect_to habit_path(params[:habit_id])
    else
      flash[:error] = 'Something went wrong'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, only: %i[destroy show]
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
      flash[:notice] = 'Succesfully logged in'
    else
      flash.now[:alert] = 'Please enter a valid name'
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Succesfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.except(:avatar))
    if @user.save
      session[:user_id] = @user.id
      @user.avatar.attach(params[:user][:avatar])
      redirect_to user_path(session[:user_id])
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      redirect_to @user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def total_hours
    habits = Habit.where(user_id: current_user.id)
    total = 0
    habits.each do |habit|
      total += habit.time * habit.repeat_days.count
    end
    h = total / 60
    m = total % 60
    "#{h},#{m}"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_icon(group)
    if group.avatar.attached?
      group.avatar
    elsif group.image
      group.image
    else
      'icon.png'
    end
  end
end

app/helpers/habits_helper.rb
# rubocop:disable Lint/ShadowingOuterLocalVariable
# rubocop:disable Layout/LineLength
module HabitsHelper
  def frequency_days(param)
    arr = []
    param.each do |el|
      arr << el.day
    end
    arr.uniq.map { |arr| arr[0] + arr[1] + arr[2] }
  end

  def group_icons(habit)
    img = habit.groups.first
    if img.avatar.attached?
      img.avatar
    elsif img.image
      img.image
    else
      'icon.png'
    end
  end

  def select_days(habit, day)
    selected_day = RepeatDay.find_by(user_id: current_user.id, day: day.to_s, habit_id: habit.id)

    if selected_day
      link_to day.to_s, repeat_day_path(day: day.to_s, habit_id: habit.id), class: 'btn-delete my-5 rounded', method: :delete
    else
      link_to day.to_s, repeat_days_path(day: day.to_s, habit_id: habit.id), class: 'btn-save my-5 rounded', method: :post
    end
  end

  def habits_user
    arr = []
    habits_with_groups = Habit.where(user_id: current_user.id)
    habits_with_groups.each do |h|
      h.groups.each do |g|
        arr << g if g.name != ''
      end
    end
    arr.uniq
  end

  def external_habits(groups)
    arr = []
    groups.each do |g|
      g.each do |el|
        arr << el
      end
    end
    arr
  end
end

# rubocop:enable Lint/ShadowingOuterLocalVariable
# rubocop:enable Layout/LineLength

app/helpers/repeat_days_helper.rb
module RepeatDaysHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_icons(user)
    !user.avatar.attached? ? '/icon.png' : user.avatar
  end

  def user_error
    return unless @user.errors.any?

    @user.errors.full_messages.each do |msg|
      @uclass = 'border border-danger' if msg.include?('Name')
    end
  end
end

app/views/common_share/_navbar.html.erb
<nav class='nav d-flex align-items-center'>
    <%= link_to user_path(current_user.id), class: 'left-btn' do %>
      <i class='fas fa-arrow-circle-left text-white'></i>
    <%end%>
    <p class="welcome m-0 text-white"><%= "Welcome #{current_user.name}!"%></p>
    <%= link_to logout_path, class: 'logout-btn' do %>
      <i class="fas fa-sign-out-alt text-white"></i>
    <%end%>
</nav>

app/views/groups/index.html.erb
<div class="habits">
  <%= render 'common_share/navbar' %>
  <br>
  <h4 class="nav-title pt-5">My Groups</h4>
    <div class="container_box">
      <% @groups.each do |group| %>
        <% date = group.created_at.to_date %>
        <%=link_to group_path(group.id) do %>
          <div class="box">
            <div class="group-icons">
              <%=image_tag(url_for(group_icon(group)))%>
            </div>
            <div class="info-group">
              <p class="mb-0"><%= group.name %></p>
              <p class="mb-0">Created at: <%=format_date(date)%></p> 
              <p class="mb-0">Created by: <%=group.user.name%></p>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>

  <%=link_to raw("<span>New Group</span>"), new_group_path, method: 'get', class: 'new-btn' %>
</div>

app/views/groups/new.html.erb
<div>
<%= render 'common_share/navbar' %>
<br>
<h1 class="nav-title pt-5">New Group
</h1>
<%= form_with(model: @group, local: true) do |form| %>
  <div>
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name, class: 'name-input rounded' %>
  </div>

  <div>
    <%= form.label :avatar, "Avatar:" %>
    <%= form.file_field :avatar, class: 'name-input rounded' %>
  </div>
  <%= form.submit "Create", class: 'btn-submit rounded mt-2 mx-1' %>
<% end %>
</div>

app/views/groups/show.html.erb
<div class="habits">
  <%= render 'common_share/navbar' %>
  <br>
  <br>
  <div class="container_box mt-4">
  
    <div class="group-icon">
      <%=image_tag(url_for(group_icon(@group)))%>
    </div>
    <div class="info-group"> 
      <h5>Group: <%= @group.name%></h5>
      <p class="m-0 pb-1">Created at: <%= "#{format_date(@group.created_at.to_date)}"%></p>
      <p class="m-0 pt-1">Created by: <%= @group.user.name%></p>
    </div>
    <%= render 'habits/habit_list', {habits: @habits} %>
  </div> 
  <p><%=link_to raw("<span>Add Habit</span>"), new_habit_path(group: @group.id), method: 'get', class: 'new-btn' %></p>
</div>

app/views/habits/_external_habit_list.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <% habits.each do |habit| %>
      <% if habit.user_id == current_user.id %>
        <div class="box mb-2">
          <div class="habit_icon">
            <%=image_tag(url_for(group_icons(habit)))%>
          </div>
          <div class="info">
            <h5 class='item-name'><%= habit.name%></h5>
              <p><%= "Created at #{format_date(habit.created_at.to_date)}"%></p>
              <p><%= "Minutes: #{habit.time} minutes" %></p>
            <% frequency_days(habit.repeat_days).each do |el| %>
              <span class="flex-row"> <%=el%></span>
            <% end %>
          </div>
        </div>
      <%end%> 
    <% end %>
</div>

app/views/habits/_form.html.erb
<%= form_with(model: @habit, local: true) do |f| %>
<p id="alert"> <%= alert %> </p>

  <div>
    <%= f.label :group_id, "Group:" %>
    <%= f.collection_select :group_id, Group.order(:name), :id, :name, class: 'name-input rounded' %>
  </div>
  <br>
  <div>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, class: 'name-input rounded'%>
  </div>
  <div>
    <%= f.label :time, "Time:" %>
    <%= f.number_field :time, placeholder: 'Time(minutes)', class: 'name-input rounded'%>
  </div>
  <div>
    <%= f.submit 'Select frequency', class: 'btn-submit rounded mt-2 mx-0' %>
  </div>
<% end %>

app/views/habits/_habit_list.html.erb
<div>
  <h2 class="nav-title">My Habits:</h2>
  <% habits.each do |habit| %>
    
    <div class="info-group">            
      <h5 class="mb-0"><%= habit.name %>
      </h5>
      <p><%= "Created at: #{format_date(habit.created_at.to_date)}"%></p>
      <p><%= "Minutes: #{habit.time} minutes" %></p>
      <p>Days:<% frequency_days(habit.repeat_days).each do |el| %>
        <%=el%>
      <% end %></p> 
      <p><%="Total time: #{habit.time * habit.repeat_days.count} minutes"%></p>
    </div>
  <% end %>
</div>

app/views/habits/external_habits.html.erb
<div class="habits">
  <%= render 'common_share/navbar' %>
  <br>
  <p id="notice"><%= notice %></p>
  <h1 class="nav-title pt-5">External Habits</h1>

  <div class="container_box">
    <% external_habits(@habits).each do |h| %>
      <div class="box">
        <div class="habit_icon">
          <%=image_tag(url_for('/icon.png'))%>
        </div>
        <div class="info">
          <h5 class='item-name'><%= h.name%></h5>
          <p><%= "Created at #{format_date(h.created_at.to_date)}"%></p>
          <p><%= "Minutes: #{h.time} minutes" %></p>
          <% frequency_days(h.repeat_days).each do |el| %>
          <span class="flex-row"> <%=el%></span>
          <% end %>
        </div>
      </div>
    <%end%>
  </div>

  <%= link_to raw("<span>New Habit</span>"), new_habit_path, method: 'get', class: 'new-btn' %>
</div>

app/views/habits/index.html.erb
<div class="habits">  
  <%= render 'common_share/navbar' %>
  <br>
  <p id="notice"><%= notice %></p>
  <h4 class="nav-title pt-5">My Total Habits:</h4><p><%="#{total_hours} hours"%></p>
  <% total_hours %>

  <div class="container_box">
    <% habits_user.each do |habit| %>
      <% habit.habits.each do |h| %>
        <%if h.user_id == current_user.id%>
          <div class="box">
            <div class="habit_icon">
            <%=image_tag(url_for(group_icons(h)))%>
            </div>
            <div class="info">
              <h5 class='item-name'><%= h.name%></h5>
              <p><%= "Created at #{format_date(h.created_at.to_date)}"%></p>
              <p><%= "Minutes: #{h.time} minutes" %></p>
              <% frequency_days(h.repeat_days).each do |el| %>
              <span class="flex-row"> <%=el%></span>
              <% end %>
            </div>
          <%end%>
        </div>
      <%end%>
    <%end%>
    
  </div>

  <%= link_to raw("<span>New Habit</span>"), new_habit_path, method: 'get', class: 'new-btn' %>
</div>

app/views/habits/new.html.erb
<br>
<br>
<div>
 <%= render 'common_share/navbar' %>
    <h1 class="nav-title pt-5">New Habits</h1>
</div>

<p><%= render 'form' %></p>

app/views/habits/show.html.erb
<%= render 'common_share/navbar' %>
<br>
<br>
<h1 class="nav-title pt-5">Select Frequency</h1>
<div>
  <label class="my-2">Days:</label><br>
  <div class="form">
  <p><%= select_days(@habit, 'Monday') %></p><br>
  <p><%= select_days(@habit, 'Tuesday') %></p><br>
  <p><%= select_days(@habit, 'Wednesday') %></p><br>
  <p><%= select_days(@habit, 'Thursday') %></p><br>
  <p><%= select_days(@habit, 'Friday') %></p><br>
  <p><%= select_days(@habit, 'Saturday') %></p><br>
  <br>
  <br>
  <br>
  <p><%= link_to 'Submit', habits_path, method: :get, class: 'btn-submit rounded'%></p>
  </div> 
  <br>
</div>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <title>Habitica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta
      property="og:title"
      content="Habitica"
    />
    <meta
      property="og:description"
      content="You can track the days and the time per habit and check the total of time that you dedicate to all of them. Users are allowed to upload their own avatar as a profile photo and also they can do the same to each group."
    />
    <meta
      property="og:image"
      content="https://raw.githubusercontent.com/janis-jenny/Habitica/development/app/assets/images/Screenshot1.jpg"
    />
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<div>
  <%= render 'common_share/navbar' %>
  <br>
  <br>
  <p id="alert"><%= alert %></p>
  <br>
  <h2 class="nav-title">Edit Account
  </h2>
  <%= form_for @user, url: {action: "update"} do |f| %>
    Name: <%= f.text_field :name, placeholder: "Only first name", class: 'name-input rounded' %><br/>
    Avatar: <%= f.file_field :avatar, class: 'name-input rounded'%>
  <%= f.submit "Edit", class: 'btn-submit rounded mt-2 mx-5' %>
  <% end %>
</div>

app/views/users/new.html.erb
<nav class='nav d-flex align-items-center'>
      <%= link_to root_path, class: 'left-btn' do %>
       <i class='fas fa-arrow-circle-left text-white px-2'></i>
      <%end%>
</nav>
<br>
<br>
<br>
<%user_error%>

<% @user.errors.full_messages.each do |msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
<br>
<div>
  <h2 class="nav-title">Sign up
  </h2>
  <%= form_for @user, url: {action: "create"} do |f| %>
    Name: <%= f.text_field :name, placeholder: "Only first name", class: 'name-input rounded #{@uclass}'%><br/>
    Avatar: <%= f.file_field :avatar, class: 'name-input rounded' %>
    <%= f.submit "Create", class: 'btn-submit rounded mt-2 mx-1'%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="show">
  <div>
    <%=image_tag(url_for(user_icons(@user)), class: 'user-icon')%>
  </div>
  <h2 class="text-white p-3"><%= @user.name %></h2>
  <ul class="d-flex flex-column align-items-center">
    <li><%= link_to "Habits", habits_path, class: 'text-white' %></li>
    <li><%= link_to "External Habits", external_habits_url, class: 'text-white' %></li>
    <li><%= link_to "Groups", groups_path, class: 'text-white' %></li>
    <li><%= link_to "Edit Account", edit_user_path, class: 'text-white' %></li>
    <li><%= link_to "Log Out", logout_path, class: 'text-white' %></li>
  </ul>
</div>